apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "argo-live-service-spa"
  description: "Freshly generated web application."
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "IvayloB84/argo-live-service-spa"
    argocd/app-name: "argo-live-service-spa"
    backstage.io/kubernetes-label-selector: "app=argo-live-service-spa"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"